[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_program = "2FRr88R8DKckqF4nkPtybffhvUM65tC2SMDwNKPx4Y1c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
